### ISSUE TITLE
I did not understand.

### ISSUE THREAD

**Issue by joaochris** [david672orford/pub-tools#1]
I didn't understand how to make it work. I tried to follow the step by step but got confused.

**Comment by david672orford** [comment]
The code in this repository is something I made for my personal use. There hasn't been a release yet and it is unfinished. But if you are interested is trying it I can answer questions about what it does and how to use it. You can ask them here.

**Comment by david672orford** [comment]
Closed due to lack of activity.

**Comment by david672orford** [comment]
Have made improvements to improve ease of use. Please see updated instructions in README.
